language: php
php:
    - 7.2
    - 7.3
    - 7.4

install:
    - composer global require squizlabs/php_codesniffer
    - composer global require phpunit/phpunit ^8

script:
    - COMPOSER_BIN=$(composer global config --absolute bin-dir)
    - $COMPOSER_BIN/phpcs --standard=PSR12 ./src ./tests
    - $COMPOSER_BIN/phpunit --bootstrap ./tests/bootstrap.php ./tests
