<?php $this->template('base.phtml', ['title' => _('Login'), 'error' => $error]); ?>

<form method="post" action="<?= url('auth#create_session') ?>">
    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

    <?php if (isset($from)): ?>
        <input type="hidden" name="from" value="<?= $from ?>" />
    <?php endif; ?>

    <div class="form-group">
        <label for="identifier"><?= _('Username or email') ?></label>
        <input
            type="text"
            name="identifier"
            id="identifier"
            required
            autofocus
            value="<?= isset($identifier) ? $identifier : '' ?>"
        />
    </div>

    <div class="form-group">
        <label for="password"><?= _('Password') ?></label>
        <input
            type="password"
            name="password"
            id="password"
            required
            value="<?= isset($password) ? $password : '' ?>"
        />
    </div>

    <div class="form-group form-group-actions">
        <button type="submit" class="button-primary button-large">
            <?= _('Log in') ?>
        </button>

        <a href="<?= url('home#index') ?>">
            <?= _('Back to homepage') ?>
        </a>
    </div>
</form>
