<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel=stylesheet type=text/css href="<?= url_static('static/style/main.css') ?>">
        <link rel=stylesheet type=text/css href="<?= url_static('static/fork-awesome/css/fork-awesome.min.css') ?>">
        <script src="<?= url_static('static/popper.min.js') ?>" defer="defer" async="async"></script>

        <?php if ($environment === 'production'): ?>
            <script src="<?= url_static('static/vue.min.js') ?>" defer="defer" async="async"></script>
        <?php else: ?>
            <script src="<?= url_static('static/vue.dev.js') ?>" defer="defer" async="async"></script>
        <?php endif; ?>

        <script src="<?= url_static('static/scripts/main.js') ?>" defer="defer" async="async"></script>

        <?php if (isset($title)): ?>
            <title><?= $title ?> · Lessy</title>
        <?php else: ?>
            <title>Lessy</title>
        <?php endif; ?>
    </head>

    <body class="layout layout-one-column <?= $current_user ? 'connected' : '' ?>">
        <header class="layout-header">
            <div class="layout-header-container">
                <a class="layout-header-home" href="<?= url('home#index') ?>">
                    <div class="app-logo flavour-normal size-small with-brand">
                        <img alt="" src="<?= url_static('static/logo.svg') ?>">
                        <span>Lessy</span>
                    </div>
                </a>

                <div class="layout-header-separator"></div>

                <?php if ($current_user): ?>
                    <div class="layout-header-right">
                        <button class="button-ghost" data-toggle-popover="user-menu">
                            <i class="fa fa-user"></i>
                            <?= $current_user->username ?>
                        </button>

                        <div class="popover" id="user-menu">
                            <form method="post" action="<?= url('auth#delete_session') ?>" class="popover-item">
                                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                                <button class="button-ghost" type="submit">
                                    <?= _('Logout') ?>
                                    <i class="fa fa-sign-out float-right"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </header>

        <main class="layout-main">
            <div class="layout-main-container">
                <?php if (isset($title)): ?>
                    <header class="layout-main-header">
                        <h1><?= $title ?></h1>
                    </header>
                <?php endif; ?>

                <?php if ($error): ?>
                    <p class="alert alert-error">
                        <?= $error ?>
                    </p>
                <?php elseif ($success): ?>
                    <p class="alert alert-success">
                        <?= $success ?>
                    </p>
                <?php endif; ?>

                <?= $this->safe('content') ?>
            </div>
        </main>
    </body>
</html>
